"""
Non-destructive migration helper for the stm32-keil skill folder.

This script updates skill-owned metadata/caches only. It never modifies user
projects generated by the skill.
"""
import argparse
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))


SKILL_DIR = Path(__file__).resolve().parent.parent
VERSION_FILE = SKILL_DIR / "skill_version.json"


def _load_version() -> dict:
    if not VERSION_FILE.exists():
        return {"name": "stm32-keil", "version": "0.0.0", "schema": 0}
    with open(VERSION_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def _ensure_dirs() -> list[str]:
    created = []
    for rel in ("data", "references", "scripts", "tests"):
        path = SKILL_DIR / rel
        if not path.exists():
            path.mkdir(parents=True, exist_ok=True)
            created.append(rel)
    return created


def _refresh_example_index() -> str:
    try:
        from example_indexer import build_index
        index_path = SKILL_DIR / "data" / "example_index.json"
        examples = SKILL_DIR / "skeleton"
        build_index(str(examples), str(index_path))
        return str(index_path)
    except Exception as exc:
        return f"skipped: {exc}"


def migrate(refresh_index: bool = False) -> dict:
    version = _load_version()
    result = {
        "skill_dir": str(SKILL_DIR),
        "version": version.get("version", "unknown"),
        "schema": version.get("schema", "unknown"),
        "created_dirs": _ensure_dirs(),
        "example_index": "not requested",
    }
    if refresh_index:
        result["example_index"] = _refresh_example_index()
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Migrate stm32-keil skill metadata")
    parser.add_argument("--refresh-index", action="store_true",
                        help="Rebuild data/example_index.json from skeleton/")
    args = parser.parse_args()
    print(json.dumps(migrate(args.refresh_index), indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
